---
excerpt_separator: <!--more-->
baseurl: ""
kramdown:
  smart_quotes: ["apos","apos","quot","quot"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title
---

